### ISSUE TITLE
Error with command-line argument  python3 ./scripts/create_cfn_stack.py \  ......

### ISSUE THREAD

**Issue by mbiombani** [garystafford/emr-demo#1]
output: ERROR - An error occurred (ParameterAlreadyExists) when calling the PutParameter operation: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.

do you have an idea?

**Comment by garystafford** [comment]
I bet put_ssm_parameter(bucket_name). The script is not very tolerant of existing parameters. No if/then logic. Does your SSM parameter store param already exist?

**Comment by garystafford** [comment]
Or you could add 'Overwrite=True' to put param method to resolve.

**Comment by mbiombani** [comment]
thanks, I had to delete the old ones  parameter store param already exist in Aws
